### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/api/services/drive/Drive$Builder

### ISSUE THREAD

**Issue by sebastianbarreiro** [jfmonteil/Pentaho-Google-Sheet-Plugin#10]
Hi, I tried this plugin but Pentaho is showing an error. I think there is any other dependency I don't have. Could you tell me if there are any other plugin or lib I need to have?

Sharing Pentaho log:
`2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Error initializing step [Arms vuelos - Diferencias con Radixx]
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : java.lang.NoClassDefFoundError: com/google/api/services/drive/Drive$Builder
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at org.pentaho.di.trans.steps.pentahogooglesheets.PentahoGoogleSheetsPluginOutput.init(PentahoGoogleSheetsPluginOutput.java:138)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at java.lang.Thread.run(Unknown Source)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - Caused by: java.lang.ClassNotFoundException: com.google.api.services.drive.Drive$Builder
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at java.net.URLClassLoader.findClass(Unknown Source)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at java.lang.ClassLoader.loadClass(Unknown Source)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at java.lang.ClassLoader.loadClass(Unknown Source)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	at java.lang.ClassLoader.loadClass(Unknown Source)
2020/12/14 11:55:45 - Arms vuelos - Diferencias con Radixx.0 - 	... 3 more
2020/12/14 11:55:47 - Arms_differences_Gsheet - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Step [Arms vuelos - Diferencias con Radixx.0] failed to initialize!`

**Comment by sebastianbarreiro** [comment]
I was using an old version of Pentaho 8.0, and some additional libs were required.
