### ISSUE TITLE
Worksheet not found error when running in server

### ISSUE THREAD

**Issue by safvanplp** [jfmonteil/Pentaho-Google-Sheet-Plugin#15]
I am able to select the 'Worksheet Id' by using the browse button. But the worksheet name itself is coming in the bar. However I am able to retrieve the data in this way in Spoon, but when I am running the same in server, it is failing with the below error.

```
2021/10/01 14:20:30 - Target Mapping Spreadsheet Input.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : Error: for worksheet : <<sheet_name>>  in spreadsheet :<<spread_sheet_key>>Resource not found:
2021/10/01 14:20:30 - Target Mapping Spreadsheet Input.0 - ERROR (version 6.1.0.1-196, build 1 from 2016-04-07 12.08.49 by buildguy) : java.io.FileNotFoundException: Resource not found:
2021/10/01 14:20:30 - Target Mapping Spreadsheet Input.0 - 	at org.pentaho.di.trans.steps.pentahogooglesheets.PentahoGoogleSheetsPluginCredentials.getCredentialsJson(PentahoGoogleSheetsPluginCredentials.java:87)
2021/10/01 14:20:30 - Target Mapping Spreadsheet Input.0 - 	at org.pentaho.di.trans.steps.pentahogooglesheets.PentahoGoogleSheetsPluginInput.init(PentahoGoogleSheetsPluginInput.java:109)
2021/10/01 14:20:30 - Target Mapping Spreadsheet Input.0 - 	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2021/10/01 14:20:30 - Target Mapping Spreadsheet Input.0 - 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jfmonteil** [comment]
Sorry, I have been out for a while, you need to move you JSON google credential file to somewhere where the server has access

**Comment by safvanplp** [comment]
Thanks @jfmonteil . It was working after placing the credential file in the correct path.
